apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: aws-registry-credential-cron
spec:
  schedule: "* */8 * * *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      backoffLimit: 4
      template:
        spec:
          serviceAccountName: ecr-update-service-account
          terminationGracePeriodSeconds: 0
          restartPolicy: Never
          containers:
          - name: updater
            imagePullPolicy: Always
            image: yndconsult/aws-kubectl:latest
            command:
              - "/run.sh"
            env:
              - name: AWS_ACCOUNT
                valueFrom:
                  secretKeyRef:
                    name: aws-secrets
                    key: aws-account
              - name: AWS_REGION
                valueFrom:
                  secretKeyRef:
                    name: aws-secrets
                    key: aws-region
              - name: NAMESPACES
                valueFrom:
                  secretKeyRef:
                    name: aws-secrets
                    key: namespaces
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: aws-secrets
                    key: aws-access-key-id
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: aws-secrets
                    key: aws-secret-access-key
